### ISSUE TITLE
Make this repo path-independent

### ISSUE THREAD

**Issue by PiotrZierhoffer** [litex-hub/litex-conda-ci#5]
As reported by @mithro in #3:

> Not really related to this patch, but why do some of the sources use;
> source ./.travis/common.sh
> While others use
> source $TRAVIS_BUILD_DIR/.travis/common.sh
> 
> We should probably make the scripts work no matter where they are put as a submodule in the parent tree? (Rather than requiring that it be .travis). For example for most of the SymbiFlow repos, we have been using .github/travis instead of .travis.

**Comment by ajelinski** [comment]
All the paths use `$CI_SCRIPTS_PATH` now so this problem is gone.
